// Mocks generated by Mockito 5.4.6 from annotations
// in core/test/data/repositories/user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:core/data/data.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponseDto_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponseDto<T> {
  _FakePaginatedResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseDto_1 extends _i1.SmartFake implements _i2.CourseDto {
  _FakeCourseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChapterDto_2 extends _i1.SmartFake implements _i2.ChapterDto {
  _FakeChapterDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseCurriculumDto_3 extends _i1.SmartFake
    implements _i2.CourseCurriculumDto {
  _FakeCourseCurriculumDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLessonDto_4 extends _i1.SmartFake implements _i2.LessonDto {
  _FakeLessonDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForumThreadDto_5 extends _i1.SmartFake
    implements _i2.ForumThreadDto {
  _FakeForumThreadDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForumCommentDto_6 extends _i1.SmartFake
    implements _i2.ForumCommentDto {
  _FakeForumCommentDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDto_7 extends _i1.SmartFake implements _i2.ProductDto {
  _FakeProductDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDto_8 extends _i1.SmartFake implements _i2.OrderDto {
  _FakeOrderDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInstallmentPlansResponseDto_9 extends _i1.SmartFake
    implements _i2.InstallmentPlansResponseDto {
  _FakeInstallmentPlansResponseDto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLearnerDto_10 extends _i1.SmartFake implements _i2.LearnerDto {
  _FakeLearnerDto_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardContentsDto_11 extends _i1.SmartFake
    implements _i2.DashboardContentsDto {
  _FakeDashboardContentsDto_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomTestConfigDto_12 extends _i1.SmartFake
    implements _i2.CustomTestConfigDto {
  _FakeCustomTestConfigDto_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAttemptDto_13 extends _i1.SmartFake implements _i2.AttemptDto {
  _FakeAttemptDto_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSectionDto_14 extends _i1.SmartFake implements _i2.SectionDto {
  _FakeSectionDto_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDto_15 extends _i1.SmartFake implements _i2.UserDto {
  _FakeUserDto_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedLoginActivityDto_16 extends _i1.SmartFake
    implements _i2.PaginatedLoginActivityDto {
  _FakePaginatedLoginActivityDto_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDoubtDto_17 extends _i1.SmartFake implements _i2.DoubtDto {
  _FakeDoubtDto_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDoubtReplyDto_18 extends _i1.SmartFake implements _i2.DoubtReplyDto {
  _FakeDoubtReplyDto_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookmarkFolderDto_19 extends _i1.SmartFake
    implements _i2.BookmarkFolderDto {
  _FakeBookmarkFolderDto_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookmarkDto_20 extends _i1.SmartFake implements _i2.BookmarkDto {
  _FakeBookmarkDto_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockitoDataSource extends _i1.Mock implements _i2.DataSource {
  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.CourseDto>> getCourses({
    int? page = 1,
    int? pageSize = 10,
    String? search,
    dynamic tags,
    bool? allowCustomTest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCourses, [], {
              #page: page,
              #pageSize: pageSize,
              #search: search,
              #tags: tags,
              #allowCustomTest: allowCustomTest,
            }),
            returnValue:
                _i3.Future<_i2.PaginatedResponseDto<_i2.CourseDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.CourseDto>(
                    this,
                    Invocation.method(#getCourses, [], {
                      #page: page,
                      #pageSize: pageSize,
                      #search: search,
                      #tags: tags,
                      #allowCustomTest: allowCustomTest,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedResponseDto<_i2.CourseDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.CourseDto>(
                    this,
                    Invocation.method(#getCourses, [], {
                      #page: page,
                      #pageSize: pageSize,
                      #search: search,
                      #tags: tags,
                      #allowCustomTest: allowCustomTest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.CourseDto>>);

  @override
  _i3.Future<_i2.CourseDto> getCourseDetail(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseDetail, [courseId]),
            returnValue: _i3.Future<_i2.CourseDto>.value(
              _FakeCourseDto_1(
                this,
                Invocation.method(#getCourseDetail, [courseId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.CourseDto>.value(
              _FakeCourseDto_1(
                this,
                Invocation.method(#getCourseDetail, [courseId]),
              ),
            ),
          )
          as _i3.Future<_i2.CourseDto>);

  @override
  _i3.Future<List<_i2.ChapterDto>> getChapters(
    String? courseId, {
    String? parentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChapters, [courseId], {#parentId: parentId}),
            returnValue: _i3.Future<List<_i2.ChapterDto>>.value(
              <_i2.ChapterDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.ChapterDto>>.value(
              <_i2.ChapterDto>[],
            ),
          )
          as _i3.Future<List<_i2.ChapterDto>>);

  @override
  _i3.Future<_i2.ChapterDto> getChapterDetail(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getChapterDetail, [slug]),
            returnValue: _i3.Future<_i2.ChapterDto>.value(
              _FakeChapterDto_2(
                this,
                Invocation.method(#getChapterDetail, [slug]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.ChapterDto>.value(
              _FakeChapterDto_2(
                this,
                Invocation.method(#getChapterDetail, [slug]),
              ),
            ),
          )
          as _i3.Future<_i2.ChapterDto>);

  @override
  _i3.Stream<_i2.CourseCurriculumDto> getCourseContents(
    String? courseId, {
    String? chapterId,
    String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCourseContents,
              [courseId],
              {#chapterId: chapterId, #type: type},
            ),
            returnValue: _i3.Stream<_i2.CourseCurriculumDto>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i2.CourseCurriculumDto>.empty(),
          )
          as _i3.Stream<_i2.CourseCurriculumDto>);

  @override
  _i3.Future<_i2.CourseCurriculumDto> getRunningContents(
    String? courseId, {
    String? chapterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRunningContents,
              [courseId],
              {#chapterId: chapterId},
            ),
            returnValue: _i3.Future<_i2.CourseCurriculumDto>.value(
              _FakeCourseCurriculumDto_3(
                this,
                Invocation.method(
                  #getRunningContents,
                  [courseId],
                  {#chapterId: chapterId},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.CourseCurriculumDto>.value(
                  _FakeCourseCurriculumDto_3(
                    this,
                    Invocation.method(
                      #getRunningContents,
                      [courseId],
                      {#chapterId: chapterId},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.CourseCurriculumDto>);

  @override
  _i3.Future<_i2.CourseCurriculumDto> getUpcomingContents(
    String? courseId, {
    String? chapterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUpcomingContents,
              [courseId],
              {#chapterId: chapterId},
            ),
            returnValue: _i3.Future<_i2.CourseCurriculumDto>.value(
              _FakeCourseCurriculumDto_3(
                this,
                Invocation.method(
                  #getUpcomingContents,
                  [courseId],
                  {#chapterId: chapterId},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.CourseCurriculumDto>.value(
                  _FakeCourseCurriculumDto_3(
                    this,
                    Invocation.method(
                      #getUpcomingContents,
                      [courseId],
                      {#chapterId: chapterId},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.CourseCurriculumDto>);

  @override
  _i3.Future<_i2.CourseCurriculumDto> getContentAttempts(
    String? courseId, {
    String? chapterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getContentAttempts,
              [courseId],
              {#chapterId: chapterId},
            ),
            returnValue: _i3.Future<_i2.CourseCurriculumDto>.value(
              _FakeCourseCurriculumDto_3(
                this,
                Invocation.method(
                  #getContentAttempts,
                  [courseId],
                  {#chapterId: chapterId},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.CourseCurriculumDto>.value(
                  _FakeCourseCurriculumDto_3(
                    this,
                    Invocation.method(
                      #getContentAttempts,
                      [courseId],
                      {#chapterId: chapterId},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.CourseCurriculumDto>);

  @override
  _i3.Future<List<_i2.LessonDto>> getLessons(String? chapterId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessons, [chapterId]),
            returnValue: _i3.Future<List<_i2.LessonDto>>.value(
              <_i2.LessonDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.LessonDto>>.value(
              <_i2.LessonDto>[],
            ),
          )
          as _i3.Future<List<_i2.LessonDto>>);

  @override
  _i3.Future<_i2.LessonDto> getLessonDetail(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonDetail, [lessonId]),
            returnValue: _i3.Future<_i2.LessonDto>.value(
              _FakeLessonDto_4(
                this,
                Invocation.method(#getLessonDetail, [lessonId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.LessonDto>.value(
              _FakeLessonDto_4(
                this,
                Invocation.method(#getLessonDetail, [lessonId]),
              ),
            ),
          )
          as _i3.Future<_i2.LessonDto>);

  @override
  _i3.Future<List<_i2.LiveClassDto>> getLiveClasses() =>
      (super.noSuchMethod(
            Invocation.method(#getLiveClasses, []),
            returnValue: _i3.Future<List<_i2.LiveClassDto>>.value(
              <_i2.LiveClassDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.LiveClassDto>>.value(
              <_i2.LiveClassDto>[],
            ),
          )
          as _i3.Future<List<_i2.LiveClassDto>>);

  @override
  _i3.Future<List<_i2.ForumCategoryDto>> getForumCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getForumCategories, []),
            returnValue: _i3.Future<List<_i2.ForumCategoryDto>>.value(
              <_i2.ForumCategoryDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.ForumCategoryDto>>.value(
                  <_i2.ForumCategoryDto>[],
                ),
          )
          as _i3.Future<List<_i2.ForumCategoryDto>>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.ForumThreadDto>> getForumThreads({
    int? page = 1,
    int? categoryId,
    String? searchQuery,
    String? sortString,
    bool? postedByMe,
    bool? commentedByMe,
    bool? likedByMe,
    bool? bookmarkedByMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getForumThreads, [], {
              #page: page,
              #categoryId: categoryId,
              #searchQuery: searchQuery,
              #sortString: sortString,
              #postedByMe: postedByMe,
              #commentedByMe: commentedByMe,
              #likedByMe: likedByMe,
              #bookmarkedByMe: bookmarkedByMe,
            }),
            returnValue:
                _i3.Future<_i2.PaginatedResponseDto<_i2.ForumThreadDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.ForumThreadDto>(
                    this,
                    Invocation.method(#getForumThreads, [], {
                      #page: page,
                      #categoryId: categoryId,
                      #searchQuery: searchQuery,
                      #sortString: sortString,
                      #postedByMe: postedByMe,
                      #commentedByMe: commentedByMe,
                      #likedByMe: likedByMe,
                      #bookmarkedByMe: bookmarkedByMe,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedResponseDto<_i2.ForumThreadDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.ForumThreadDto>(
                    this,
                    Invocation.method(#getForumThreads, [], {
                      #page: page,
                      #categoryId: categoryId,
                      #searchQuery: searchQuery,
                      #sortString: sortString,
                      #postedByMe: postedByMe,
                      #commentedByMe: commentedByMe,
                      #likedByMe: likedByMe,
                      #bookmarkedByMe: bookmarkedByMe,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.ForumThreadDto>>);

  @override
  _i3.Future<_i2.ForumThreadDto> getForumThread(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getForumThread, [slug]),
            returnValue: _i3.Future<_i2.ForumThreadDto>.value(
              _FakeForumThreadDto_5(
                this,
                Invocation.method(#getForumThread, [slug]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.ForumThreadDto>.value(
              _FakeForumThreadDto_5(
                this,
                Invocation.method(#getForumThread, [slug]),
              ),
            ),
          )
          as _i3.Future<_i2.ForumThreadDto>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.ForumCommentDto>> getForumComments({
    required int? threadId,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getForumComments, [], {
              #threadId: threadId,
              #page: page,
            }),
            returnValue:
                _i3.Future<_i2.PaginatedResponseDto<_i2.ForumCommentDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.ForumCommentDto>(
                    this,
                    Invocation.method(#getForumComments, [], {
                      #threadId: threadId,
                      #page: page,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedResponseDto<_i2.ForumCommentDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.ForumCommentDto>(
                    this,
                    Invocation.method(#getForumComments, [], {
                      #threadId: threadId,
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.ForumCommentDto>>);

  @override
  _i3.Future<_i2.ForumCommentDto> postForumComment({
    required int? threadId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postForumComment, [], {
              #threadId: threadId,
              #content: content,
            }),
            returnValue: _i3.Future<_i2.ForumCommentDto>.value(
              _FakeForumCommentDto_6(
                this,
                Invocation.method(#postForumComment, [], {
                  #threadId: threadId,
                  #content: content,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.ForumCommentDto>.value(
              _FakeForumCommentDto_6(
                this,
                Invocation.method(#postForumComment, [], {
                  #threadId: threadId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.ForumCommentDto>);

  @override
  _i3.Future<_i2.ForumThreadDto> postForumThread({
    required String? title,
    required String? contentHtml,
    required String? categorySlug,
    String? courseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postForumThread, [], {
              #title: title,
              #contentHtml: contentHtml,
              #categorySlug: categorySlug,
              #courseId: courseId,
            }),
            returnValue: _i3.Future<_i2.ForumThreadDto>.value(
              _FakeForumThreadDto_5(
                this,
                Invocation.method(#postForumThread, [], {
                  #title: title,
                  #contentHtml: contentHtml,
                  #categorySlug: categorySlug,
                  #courseId: courseId,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.ForumThreadDto>.value(
              _FakeForumThreadDto_5(
                this,
                Invocation.method(#postForumThread, [], {
                  #title: title,
                  #contentHtml: contentHtml,
                  #categorySlug: categorySlug,
                  #courseId: courseId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.ForumThreadDto>);

  @override
  _i3.Future<String> uploadImage(_i4.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [file]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [file]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [file]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i2.UserProgressDto>> getUserProgress(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProgress, [userId]),
            returnValue: _i3.Future<List<_i2.UserProgressDto>>.value(
              <_i2.UserProgressDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.UserProgressDto>>.value(
                  <_i2.UserProgressDto>[],
                ),
          )
          as _i3.Future<List<_i2.UserProgressDto>>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.ProductCategoryDto>>
  getProductCategories({int? page = 1, String? search}) =>
      (super.noSuchMethod(
            Invocation.method(#getProductCategories, [], {
              #page: page,
              #search: search,
            }),
            returnValue:
                _i3.Future<
                  _i2.PaginatedResponseDto<_i2.ProductCategoryDto>
                >.value(
                  _FakePaginatedResponseDto_0<_i2.ProductCategoryDto>(
                    this,
                    Invocation.method(#getProductCategories, [], {
                      #page: page,
                      #search: search,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i2.PaginatedResponseDto<_i2.ProductCategoryDto>
                >.value(
                  _FakePaginatedResponseDto_0<_i2.ProductCategoryDto>(
                    this,
                    Invocation.method(#getProductCategories, [], {
                      #page: page,
                      #search: search,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.ProductCategoryDto>>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.ProductDto>> getProducts({
    int? page = 1,
    String? category,
    String? categoryName,
    String? tag,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #page: page,
              #category: category,
              #categoryName: categoryName,
              #tag: tag,
              #search: search,
            }),
            returnValue:
                _i3.Future<_i2.PaginatedResponseDto<_i2.ProductDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.ProductDto>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #page: page,
                      #category: category,
                      #categoryName: categoryName,
                      #tag: tag,
                      #search: search,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedResponseDto<_i2.ProductDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.ProductDto>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #page: page,
                      #category: category,
                      #categoryName: categoryName,
                      #tag: tag,
                      #search: search,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.ProductDto>>);

  @override
  _i3.Future<_i2.ProductDto> getProduct(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [slug]),
            returnValue: _i3.Future<_i2.ProductDto>.value(
              _FakeProductDto_7(this, Invocation.method(#getProduct, [slug])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.ProductDto>.value(
              _FakeProductDto_7(this, Invocation.method(#getProduct, [slug])),
            ),
          )
          as _i3.Future<_i2.ProductDto>);

  @override
  _i3.Future<_i2.OrderDto> createOrder(String? productSlug) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [productSlug]),
            returnValue: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#createOrder, [productSlug]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#createOrder, [productSlug]),
              ),
            ),
          )
          as _i3.Future<_i2.OrderDto>);

  @override
  _i3.Future<_i2.OrderDto> confirmOrder(
    int? orderId,
    Map<String, dynamic>? billingDetails,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmOrder, [orderId, billingDetails]),
            returnValue: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#confirmOrder, [orderId, billingDetails]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#confirmOrder, [orderId, billingDetails]),
              ),
            ),
          )
          as _i3.Future<_i2.OrderDto>);

  @override
  _i3.Future<_i2.OrderDto> refreshOrderStatus(int? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshOrderStatus, [orderId]),
            returnValue: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#refreshOrderStatus, [orderId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#refreshOrderStatus, [orderId]),
              ),
            ),
          )
          as _i3.Future<_i2.OrderDto>);

  @override
  _i3.Future<String> generatePayUHash(String? hashString) =>
      (super.noSuchMethod(
            Invocation.method(#generatePayUHash, [hashString]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generatePayUHash, [hashString]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generatePayUHash, [hashString]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i2.OrderDto> applyCoupon(int? orderId, String? couponCode) =>
      (super.noSuchMethod(
            Invocation.method(#applyCoupon, [orderId, couponCode]),
            returnValue: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#applyCoupon, [orderId, couponCode]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.OrderDto>.value(
              _FakeOrderDto_8(
                this,
                Invocation.method(#applyCoupon, [orderId, couponCode]),
              ),
            ),
          )
          as _i3.Future<_i2.OrderDto>);

  @override
  _i3.Future<_i2.InstallmentPlansResponseDto> getInstallmentPlans(
    String? slug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInstallmentPlans, [slug]),
            returnValue: _i3.Future<_i2.InstallmentPlansResponseDto>.value(
              _FakeInstallmentPlansResponseDto_9(
                this,
                Invocation.method(#getInstallmentPlans, [slug]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.InstallmentPlansResponseDto>.value(
                  _FakeInstallmentPlansResponseDto_9(
                    this,
                    Invocation.method(#getInstallmentPlans, [slug]),
                  ),
                ),
          )
          as _i3.Future<_i2.InstallmentPlansResponseDto>);

  @override
  _i3.Future<List<_i2.DashboardBannerDto>> getDashboardBanners() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardBanners, []),
            returnValue: _i3.Future<List<_i2.DashboardBannerDto>>.value(
              <_i2.DashboardBannerDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.DashboardBannerDto>>.value(
                  <_i2.DashboardBannerDto>[],
                ),
          )
          as _i3.Future<List<_i2.DashboardBannerDto>>);

  @override
  _i3.Future<List<_i2.LearnerDto>> fetchLeaderboard({
    required _i2.LeaderboardTimeline? timeline,
    int? limit = 10,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLeaderboard, [], {
              #timeline: timeline,
              #limit: limit,
              #page: page,
            }),
            returnValue: _i3.Future<List<_i2.LearnerDto>>.value(
              <_i2.LearnerDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.LearnerDto>>.value(
              <_i2.LearnerDto>[],
            ),
          )
          as _i3.Future<List<_i2.LearnerDto>>);

  @override
  _i3.Future<_i2.LearnerDto> fetchMyRank() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyRank, []),
            returnValue: _i3.Future<_i2.LearnerDto>.value(
              _FakeLearnerDto_10(this, Invocation.method(#fetchMyRank, [])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.LearnerDto>.value(
              _FakeLearnerDto_10(this, Invocation.method(#fetchMyRank, [])),
            ),
          )
          as _i3.Future<_i2.LearnerDto>);

  @override
  _i3.Future<List<_i2.LearnerDto>> fetchCompetitorTargets() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCompetitorTargets, []),
            returnValue: _i3.Future<List<_i2.LearnerDto>>.value(
              <_i2.LearnerDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.LearnerDto>>.value(
              <_i2.LearnerDto>[],
            ),
          )
          as _i3.Future<List<_i2.LearnerDto>>);

  @override
  _i3.Future<List<_i2.LearnerDto>> fetchCompetitorThreats() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCompetitorThreats, []),
            returnValue: _i3.Future<List<_i2.LearnerDto>>.value(
              <_i2.LearnerDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.LearnerDto>>.value(
              <_i2.LearnerDto>[],
            ),
          )
          as _i3.Future<List<_i2.LearnerDto>>);

  @override
  _i3.Future<_i2.DashboardContentsDto> getWhatsNewFeed(
    _i2.DashboardSectionType? sectionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWhatsNewFeed, [sectionType]),
            returnValue: _i3.Future<_i2.DashboardContentsDto>.value(
              _FakeDashboardContentsDto_11(
                this,
                Invocation.method(#getWhatsNewFeed, [sectionType]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.DashboardContentsDto>.value(
                  _FakeDashboardContentsDto_11(
                    this,
                    Invocation.method(#getWhatsNewFeed, [sectionType]),
                  ),
                ),
          )
          as _i3.Future<_i2.DashboardContentsDto>);

  @override
  _i3.Future<_i2.DashboardContentsDto> getResumeLearningFeed(
    _i2.DashboardSectionType? sectionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getResumeLearningFeed, [sectionType]),
            returnValue: _i3.Future<_i2.DashboardContentsDto>.value(
              _FakeDashboardContentsDto_11(
                this,
                Invocation.method(#getResumeLearningFeed, [sectionType]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.DashboardContentsDto>.value(
                  _FakeDashboardContentsDto_11(
                    this,
                    Invocation.method(#getResumeLearningFeed, [sectionType]),
                  ),
                ),
          )
          as _i3.Future<_i2.DashboardContentsDto>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.PostDto>> getPosts({
    int? page = 1,
    String? categorySlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {
              #page: page,
              #categorySlug: categorySlug,
            }),
            returnValue:
                _i3.Future<_i2.PaginatedResponseDto<_i2.PostDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.PostDto>(
                    this,
                    Invocation.method(#getPosts, [], {
                      #page: page,
                      #categorySlug: categorySlug,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedResponseDto<_i2.PostDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.PostDto>(
                    this,
                    Invocation.method(#getPosts, [], {
                      #page: page,
                      #categorySlug: categorySlug,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.PostDto>>);

  @override
  _i3.Future<List<_i2.PostCategoryDto>> getPostCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getPostCategories, []),
            returnValue: _i3.Future<List<_i2.PostCategoryDto>>.value(
              <_i2.PostCategoryDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.PostCategoryDto>>.value(
                  <_i2.PostCategoryDto>[],
                ),
          )
          as _i3.Future<List<_i2.PostCategoryDto>>);

  @override
  _i3.Future<_i2.CustomTestConfigDto> getCustomTestConfig(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomTestConfig, [courseId]),
            returnValue: _i3.Future<_i2.CustomTestConfigDto>.value(
              _FakeCustomTestConfigDto_12(
                this,
                Invocation.method(#getCustomTestConfig, [courseId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.CustomTestConfigDto>.value(
                  _FakeCustomTestConfigDto_12(
                    this,
                    Invocation.method(#getCustomTestConfig, [courseId]),
                  ),
                ),
          )
          as _i3.Future<_i2.CustomTestConfigDto>);

  @override
  _i3.Future<_i2.AttemptDto> generateCustomExam(
    _i2.CustomExamGenerationRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateCustomExam, [request]),
            returnValue: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#generateCustomExam, [request]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#generateCustomExam, [request]),
              ),
            ),
          )
          as _i3.Future<_i2.AttemptDto>);

  @override
  _i3.Future<List<_i2.AttemptDto>> getAttempts(String? attemptsUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getAttempts, [attemptsUrl]),
            returnValue: _i3.Future<List<_i2.AttemptDto>>.value(
              <_i2.AttemptDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.AttemptDto>>.value(
              <_i2.AttemptDto>[],
            ),
          )
          as _i3.Future<List<_i2.AttemptDto>>);

  @override
  _i3.Future<_i2.AttemptDto> createAttempt(
    String? attemptsUrl, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAttempt, [attemptsUrl], {#data: data}),
            returnValue: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#createAttempt, [attemptsUrl], {#data: data}),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#createAttempt, [attemptsUrl], {#data: data}),
              ),
            ),
          )
          as _i3.Future<_i2.AttemptDto>);

  @override
  _i3.Future<_i2.AttemptDto> createContentAttempt(
    String? contentAttemptsUrl, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createContentAttempt,
              [contentAttemptsUrl],
              {#data: data},
            ),
            returnValue: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(
                  #createContentAttempt,
                  [contentAttemptsUrl],
                  {#data: data},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(
                  #createContentAttempt,
                  [contentAttemptsUrl],
                  {#data: data},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.AttemptDto>);

  @override
  _i3.Future<_i2.AttemptDto> startAttempt(String? attemptId) =>
      (super.noSuchMethod(
            Invocation.method(#startAttempt, [attemptId]),
            returnValue: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#startAttempt, [attemptId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#startAttempt, [attemptId]),
              ),
            ),
          )
          as _i3.Future<_i2.AttemptDto>);

  @override
  _i3.Future<List<_i2.QuestionDto>> getQuestions(String? attemptId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestions, [attemptId]),
            returnValue: _i3.Future<List<_i2.QuestionDto>>.value(
              <_i2.QuestionDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.QuestionDto>>.value(
              <_i2.QuestionDto>[],
            ),
          )
          as _i3.Future<List<_i2.QuestionDto>>);

  @override
  _i3.Future<List<_i2.QuestionDto>> getOfflineExamQuestions(String? examId) =>
      (super.noSuchMethod(
            Invocation.method(#getOfflineExamQuestions, [examId]),
            returnValue: _i3.Future<List<_i2.QuestionDto>>.value(
              <_i2.QuestionDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i2.QuestionDto>>.value(
              <_i2.QuestionDto>[],
            ),
          )
          as _i3.Future<List<_i2.QuestionDto>>);

  @override
  _i3.Future<void> submitOfflineExamAnswers(
    String? examId,
    Map<String, dynamic>? payload,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitOfflineExamAnswers, [examId, payload]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.QuizReviewResultDto?> submitAnswer(
    String? attemptId,
    String? questionId,
    _i2.AnswerDto? answer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnswer, [attemptId, questionId, answer]),
            returnValue: _i3.Future<_i2.QuizReviewResultDto?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i2.QuizReviewResultDto?>.value(),
          )
          as _i3.Future<_i2.QuizReviewResultDto?>);

  @override
  _i3.Future<void> reportQuestion(
    String? questionId,
    Map<String, dynamic>? payload,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reportQuestion, [questionId, payload]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.AttemptDto> sendHeartbeat(String? attemptId) =>
      (super.noSuchMethod(
            Invocation.method(#sendHeartbeat, [attemptId]),
            returnValue: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#sendHeartbeat, [attemptId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(#sendHeartbeat, [attemptId]),
              ),
            ),
          )
          as _i3.Future<_i2.AttemptDto>);

  @override
  _i3.Future<String?> getLastWatchedPosition(String? attemptsUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getLastWatchedPosition, [attemptsUrl]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> updateVideoAttempt({
    required int? chapterContentId,
    required String? lastWatchPosition,
    required List<List<double>>? watchedTimeRanges,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateVideoAttempt, [], {
              #chapterContentId: chapterContentId,
              #lastWatchPosition: lastWatchPosition,
              #watchedTimeRanges: watchedTimeRanges,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.AttemptDto> endExam(
    String? attemptId, {
    bool? isContentExam = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #endExam,
              [attemptId],
              {#isContentExam: isContentExam},
            ),
            returnValue: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(
                  #endExam,
                  [attemptId],
                  {#isContentExam: isContentExam},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AttemptDto>.value(
              _FakeAttemptDto_13(
                this,
                Invocation.method(
                  #endExam,
                  [attemptId],
                  {#isContentExam: isContentExam},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.AttemptDto>);

  @override
  _i3.Future<List<_i2.ReviewItemDto>> getReviewItems(String? reviewUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewItems, [reviewUrl]),
            returnValue: _i3.Future<List<_i2.ReviewItemDto>>.value(
              <_i2.ReviewItemDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.ReviewItemDto>>.value(
                  <_i2.ReviewItemDto>[],
                ),
          )
          as _i3.Future<List<_i2.ReviewItemDto>>);

  @override
  _i3.Future<List<_i2.SubjectAnalyticsDto>> getSubjectAnalytics(
    String? analyticsUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectAnalytics, [analyticsUrl]),
            returnValue: _i3.Future<List<_i2.SubjectAnalyticsDto>>.value(
              <_i2.SubjectAnalyticsDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.SubjectAnalyticsDto>>.value(
                  <_i2.SubjectAnalyticsDto>[],
                ),
          )
          as _i3.Future<List<_i2.SubjectAnalyticsDto>>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.SubjectAnalyticsDto>>
  getAnalyticsData({int? page = 1, int? parentId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAnalyticsData, [], {
              #page: page,
              #parentId: parentId,
            }),
            returnValue:
                _i3.Future<
                  _i2.PaginatedResponseDto<_i2.SubjectAnalyticsDto>
                >.value(
                  _FakePaginatedResponseDto_0<_i2.SubjectAnalyticsDto>(
                    this,
                    Invocation.method(#getAnalyticsData, [], {
                      #page: page,
                      #parentId: parentId,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i2.PaginatedResponseDto<_i2.SubjectAnalyticsDto>
                >.value(
                  _FakePaginatedResponseDto_0<_i2.SubjectAnalyticsDto>(
                    this,
                    Invocation.method(#getAnalyticsData, [], {
                      #page: page,
                      #parentId: parentId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.SubjectAnalyticsDto>>);

  @override
  _i3.Future<_i2.SectionDto> startSection(
    String? attemptId,
    String? sectionOrder,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startSection, [attemptId, sectionOrder]),
            returnValue: _i3.Future<_i2.SectionDto>.value(
              _FakeSectionDto_14(
                this,
                Invocation.method(#startSection, [attemptId, sectionOrder]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.SectionDto>.value(
              _FakeSectionDto_14(
                this,
                Invocation.method(#startSection, [attemptId, sectionOrder]),
              ),
            ),
          )
          as _i3.Future<_i2.SectionDto>);

  @override
  _i3.Future<_i2.SectionDto> endSection(
    String? attemptId,
    String? sectionOrder,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#endSection, [attemptId, sectionOrder]),
            returnValue: _i3.Future<_i2.SectionDto>.value(
              _FakeSectionDto_14(
                this,
                Invocation.method(#endSection, [attemptId, sectionOrder]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.SectionDto>.value(
              _FakeSectionDto_14(
                this,
                Invocation.method(#endSection, [attemptId, sectionOrder]),
              ),
            ),
          )
          as _i3.Future<_i2.SectionDto>);

  @override
  _i3.Future<_i2.DashboardContentsDto> getRecentlyCompletedFeed(
    _i2.DashboardSectionType? sectionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyCompletedFeed, [sectionType]),
            returnValue: _i3.Future<_i2.DashboardContentsDto>.value(
              _FakeDashboardContentsDto_11(
                this,
                Invocation.method(#getRecentlyCompletedFeed, [sectionType]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.DashboardContentsDto>.value(
                  _FakeDashboardContentsDto_11(
                    this,
                    Invocation.method(#getRecentlyCompletedFeed, [sectionType]),
                  ),
                ),
          )
          as _i3.Future<_i2.DashboardContentsDto>);

  @override
  _i3.Future<_i2.UserDto> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i3.Future<_i2.UserDto>.value(
              _FakeUserDto_15(this, Invocation.method(#getProfile, [])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.UserDto>.value(
              _FakeUserDto_15(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i3.Future<_i2.UserDto>);

  @override
  _i3.Future<_i2.UserDto> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [data]),
            returnValue: _i3.Future<_i2.UserDto>.value(
              _FakeUserDto_15(this, Invocation.method(#updateProfile, [data])),
            ),
            returnValueForMissingStub: _i3.Future<_i2.UserDto>.value(
              _FakeUserDto_15(this, Invocation.method(#updateProfile, [data])),
            ),
          )
          as _i3.Future<_i2.UserDto>);

  @override
  _i3.Future<_i2.PaginatedLoginActivityDto> getLoginActivity({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getLoginActivity, [], {#page: page}),
            returnValue: _i3.Future<_i2.PaginatedLoginActivityDto>.value(
              _FakePaginatedLoginActivityDto_16(
                this,
                Invocation.method(#getLoginActivity, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedLoginActivityDto>.value(
                  _FakePaginatedLoginActivityDto_16(
                    this,
                    Invocation.method(#getLoginActivity, [], {#page: page}),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedLoginActivityDto>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.DoubtDto>> getDoubts({
    int? page = 1,
    String? searchQuery,
    int? chapterContentId,
    String? queryType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDoubts, [], {
              #page: page,
              #searchQuery: searchQuery,
              #chapterContentId: chapterContentId,
              #queryType: queryType,
            }),
            returnValue:
                _i3.Future<_i2.PaginatedResponseDto<_i2.DoubtDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.DoubtDto>(
                    this,
                    Invocation.method(#getDoubts, [], {
                      #page: page,
                      #searchQuery: searchQuery,
                      #chapterContentId: chapterContentId,
                      #queryType: queryType,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedResponseDto<_i2.DoubtDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.DoubtDto>(
                    this,
                    Invocation.method(#getDoubts, [], {
                      #page: page,
                      #searchQuery: searchQuery,
                      #chapterContentId: chapterContentId,
                      #queryType: queryType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.DoubtDto>>);

  @override
  _i3.Future<({_i2.DoubtDto doubt, List<_i2.DoubtReplyDto> replies})>
  getDoubtReplies(String? doubtId) =>
      (super.noSuchMethod(
            Invocation.method(#getDoubtReplies, [doubtId]),
            returnValue:
                _i3.Future<
                  ({_i2.DoubtDto doubt, List<_i2.DoubtReplyDto> replies})
                >.value((
                  doubt: _FakeDoubtDto_17(
                    this,
                    Invocation.method(#getDoubtReplies, [doubtId]),
                  ),
                  replies: <_i2.DoubtReplyDto>[],
                )),
            returnValueForMissingStub:
                _i3.Future<
                  ({_i2.DoubtDto doubt, List<_i2.DoubtReplyDto> replies})
                >.value((
                  doubt: _FakeDoubtDto_17(
                    this,
                    Invocation.method(#getDoubtReplies, [doubtId]),
                  ),
                  replies: <_i2.DoubtReplyDto>[],
                )),
          )
          as _i3.Future<
            ({_i2.DoubtDto doubt, List<_i2.DoubtReplyDto> replies})
          >);

  @override
  _i3.Future<List<_i2.DoubtTopicDto>> getDoubtTopics({int? parentId}) =>
      (super.noSuchMethod(
            Invocation.method(#getDoubtTopics, [], {#parentId: parentId}),
            returnValue: _i3.Future<List<_i2.DoubtTopicDto>>.value(
              <_i2.DoubtTopicDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.DoubtTopicDto>>.value(
                  <_i2.DoubtTopicDto>[],
                ),
          )
          as _i3.Future<List<_i2.DoubtTopicDto>>);

  @override
  _i3.Future<_i2.DoubtDto> createDoubt({
    required String? title,
    required String? description,
    int? topicId,
    int? chapterContentId,
    int? questionId,
    int? queryType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDoubt, [], {
              #title: title,
              #description: description,
              #topicId: topicId,
              #chapterContentId: chapterContentId,
              #questionId: questionId,
              #queryType: queryType,
            }),
            returnValue: _i3.Future<_i2.DoubtDto>.value(
              _FakeDoubtDto_17(
                this,
                Invocation.method(#createDoubt, [], {
                  #title: title,
                  #description: description,
                  #topicId: topicId,
                  #chapterContentId: chapterContentId,
                  #questionId: questionId,
                  #queryType: queryType,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.DoubtDto>.value(
              _FakeDoubtDto_17(
                this,
                Invocation.method(#createDoubt, [], {
                  #title: title,
                  #description: description,
                  #topicId: topicId,
                  #chapterContentId: chapterContentId,
                  #questionId: questionId,
                  #queryType: queryType,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.DoubtDto>);

  @override
  _i3.Future<_i2.DoubtReplyDto> postDoubtReply({
    required String? doubtId,
    String? comment,
    bool? shouldResolve,
    bool? shouldClose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postDoubtReply, [], {
              #doubtId: doubtId,
              #comment: comment,
              #shouldResolve: shouldResolve,
              #shouldClose: shouldClose,
            }),
            returnValue: _i3.Future<_i2.DoubtReplyDto>.value(
              _FakeDoubtReplyDto_18(
                this,
                Invocation.method(#postDoubtReply, [], {
                  #doubtId: doubtId,
                  #comment: comment,
                  #shouldResolve: shouldResolve,
                  #shouldClose: shouldClose,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.DoubtReplyDto>.value(
              _FakeDoubtReplyDto_18(
                this,
                Invocation.method(#postDoubtReply, [], {
                  #doubtId: doubtId,
                  #comment: comment,
                  #shouldResolve: shouldResolve,
                  #shouldClose: shouldClose,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.DoubtReplyDto>);

  @override
  _i3.Future<String> uploadDoubtImage(_i4.File? file, {int? ticketId}) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDoubtImage, [file], {#ticketId: ticketId}),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadDoubtImage,
                  [file],
                  {#ticketId: ticketId},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadDoubtImage,
                  [file],
                  {#ticketId: ticketId},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> markLessonCompleted(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#markLessonCompleted, [lessonId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> downloadFile({
    required String? url,
    required String? savePath,
    void Function(int, int)? onReceiveProgress,
    dynamic cancelToken,
    bool? requireAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [], {
              #url: url,
              #savePath: savePath,
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #requireAuth: requireAuth,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.BookmarkFolderDto>> getBookmarkFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkFolders, []),
            returnValue: _i3.Future<List<_i2.BookmarkFolderDto>>.value(
              <_i2.BookmarkFolderDto>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.BookmarkFolderDto>>.value(
                  <_i2.BookmarkFolderDto>[],
                ),
          )
          as _i3.Future<List<_i2.BookmarkFolderDto>>);

  @override
  _i3.Future<_i2.PaginatedResponseDto<_i2.BookmarkDto>> getBookmarks({
    int? page = 1,
    String? folder,
    String? order,
    String? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarks, [], {
              #page: page,
              #folder: folder,
              #order: order,
              #filter: filter,
            }),
            returnValue:
                _i3.Future<_i2.PaginatedResponseDto<_i2.BookmarkDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.BookmarkDto>(
                    this,
                    Invocation.method(#getBookmarks, [], {
                      #page: page,
                      #folder: folder,
                      #order: order,
                      #filter: filter,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i2.PaginatedResponseDto<_i2.BookmarkDto>>.value(
                  _FakePaginatedResponseDto_0<_i2.BookmarkDto>(
                    this,
                    Invocation.method(#getBookmarks, [], {
                      #page: page,
                      #folder: folder,
                      #order: order,
                      #filter: filter,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginatedResponseDto<_i2.BookmarkDto>>);

  @override
  _i3.Future<_i2.BookmarkFolderDto> createBookmarkFolder(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createBookmarkFolder, [name]),
            returnValue: _i3.Future<_i2.BookmarkFolderDto>.value(
              _FakeBookmarkFolderDto_19(
                this,
                Invocation.method(#createBookmarkFolder, [name]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.BookmarkFolderDto>.value(
              _FakeBookmarkFolderDto_19(
                this,
                Invocation.method(#createBookmarkFolder, [name]),
              ),
            ),
          )
          as _i3.Future<_i2.BookmarkFolderDto>);

  @override
  _i3.Future<_i2.BookmarkFolderDto> updateBookmarkFolder(
    int? id,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBookmarkFolder, [id, name]),
            returnValue: _i3.Future<_i2.BookmarkFolderDto>.value(
              _FakeBookmarkFolderDto_19(
                this,
                Invocation.method(#updateBookmarkFolder, [id, name]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.BookmarkFolderDto>.value(
              _FakeBookmarkFolderDto_19(
                this,
                Invocation.method(#updateBookmarkFolder, [id, name]),
              ),
            ),
          )
          as _i3.Future<_i2.BookmarkFolderDto>);

  @override
  _i3.Future<void> deleteBookmarkFolder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmarkFolder, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.BookmarkDto> createBookmark({
    required String? category,
    required int? lessonId,
    String? folder,
    String? bookmarkType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBookmark, [], {
              #category: category,
              #lessonId: lessonId,
              #folder: folder,
              #bookmarkType: bookmarkType,
            }),
            returnValue: _i3.Future<_i2.BookmarkDto>.value(
              _FakeBookmarkDto_20(
                this,
                Invocation.method(#createBookmark, [], {
                  #category: category,
                  #lessonId: lessonId,
                  #folder: folder,
                  #bookmarkType: bookmarkType,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.BookmarkDto>.value(
              _FakeBookmarkDto_20(
                this,
                Invocation.method(#createBookmark, [], {
                  #category: category,
                  #lessonId: lessonId,
                  #folder: folder,
                  #bookmarkType: bookmarkType,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.BookmarkDto>);

  @override
  _i3.Future<void> deleteBookmark(String? bookmarkId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [bookmarkId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
