// Mocks generated by Mockito 5.4.6 from annotations
// in core/test/data/auth/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core/data/auth/auth_api_service.dart' as _i2;
import 'package:core/data/auth/auth_local_data_source.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthApiResult_0 extends _i1.SmartFake implements _i2.AuthApiResult {
  _FakeAuthApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i2.AuthApiService {
  @override
  _i3.Future<_i2.AuthApiResult> loginWithPassword({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithPassword, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i3.Future<_i2.AuthApiResult>.value(
              _FakeAuthApiResult_0(
                this,
                Invocation.method(#loginWithPassword, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AuthApiResult>.value(
              _FakeAuthApiResult_0(
                this,
                Invocation.method(#loginWithPassword, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.AuthApiResult>);

  @override
  _i3.Future<void> generateOtp({
    required String? phoneNumber,
    required String? countryCode,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateOtp, [], {
              #phoneNumber: phoneNumber,
              #countryCode: countryCode,
              #email: email,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.AuthApiResult> verifyOtp({
    required String? otp,
    required String? phoneNumber,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #otp: otp,
              #phoneNumber: phoneNumber,
              #email: email,
            }),
            returnValue: _i3.Future<_i2.AuthApiResult>.value(
              _FakeAuthApiResult_0(
                this,
                Invocation.method(#verifyOtp, [], {
                  #otp: otp,
                  #phoneNumber: phoneNumber,
                  #email: email,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.AuthApiResult>.value(
              _FakeAuthApiResult_0(
                this,
                Invocation.method(#verifyOtp, [], {
                  #otp: otp,
                  #phoneNumber: phoneNumber,
                  #email: email,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.AuthApiResult>);

  @override
  _i3.Future<void> logout({String? authToken}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#authToken: authToken}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i4.AuthLocalDataSource {
  @override
  _i3.Future<bool> isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
