// Mocks generated by Mockito 5.4.6 from annotations
// in core/test/data/providers/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/data/auth/auth_repository.dart' as _i5;
import 'package:core/data/data.dart' as _i2;
import 'package:core/data/repositories/user_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDto_0 extends _i1.SmartFake implements _i2.UserDto {
  _FakeUserDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedLoginActivityDto_1 extends _i1.SmartFake
    implements _i2.PaginatedLoginActivityDto {
  _FakePaginatedLoginActivityDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  @override
  _i4.Stream<_i2.UsersTableData?> watchCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#watchCurrentUser, []),
            returnValue: _i4.Stream<_i2.UsersTableData?>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.UsersTableData?>.empty(),
          )
          as _i4.Stream<_i2.UsersTableData?>);

  @override
  _i4.Future<_i2.UsersTableData?> getCurrentProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfile, []),
            returnValue: _i4.Future<_i2.UsersTableData?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.UsersTableData?>.value(),
          )
          as _i4.Future<_i2.UsersTableData?>);

  @override
  _i4.Future<_i2.UserDto> refreshProfile() =>
      (super.noSuchMethod(
            Invocation.method(#refreshProfile, []),
            returnValue: _i4.Future<_i2.UserDto>.value(
              _FakeUserDto_0(this, Invocation.method(#refreshProfile, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserDto>.value(
              _FakeUserDto_0(this, Invocation.method(#refreshProfile, [])),
            ),
          )
          as _i4.Future<_i2.UserDto>);

  @override
  _i4.Future<void> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.PaginatedLoginActivityDto> getLoginActivity({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getLoginActivity, [], {#page: page}),
            returnValue: _i4.Future<_i2.PaginatedLoginActivityDto>.value(
              _FakePaginatedLoginActivityDto_1(
                this,
                Invocation.method(#getLoginActivity, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.PaginatedLoginActivityDto>.value(
                  _FakePaginatedLoginActivityDto_1(
                    this,
                    Invocation.method(#getLoginActivity, [], {#page: page}),
                  ),
                ),
          )
          as _i4.Future<_i2.PaginatedLoginActivityDto>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  @override
  _i4.Future<bool> isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> loginWithPassword({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithPassword, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> register({
    required String? username,
    required String? email,
    required String? password,
    String? phone,
    String? countryCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #email: email,
              #password: password,
              #phone: phone,
              #countryCode: countryCode,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> generateOtp({
    required String? phoneNumber,
    required String? countryCode,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateOtp, [], {
              #phoneNumber: phoneNumber,
              #countryCode: countryCode,
              #email: email,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifyOtp({
    required String? otp,
    required String? phoneNumber,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #otp: otp,
              #phoneNumber: phoneNumber,
              #email: email,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logoutOtherDevices() =>
      (super.noSuchMethod(
            Invocation.method(#logoutOtherDevices, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifyLogin() =>
      (super.noSuchMethod(
            Invocation.method(#verifyLogin, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
