name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  testpress:
    path: ../packages/testpress
  core:
    path: ../packages/core
  courses:
    path: ../packages/courses
  explore:
    path: ../packages/explore
  profile:
    path: ../packages/profile
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
